#!/usr/bin/env python3
"""
rebuild-indexes.py — Regenerate auto-generated INDEX.md files from
frontmatter `description:` fields.

A folder gets an auto-generated INDEX.md only if it contains a README.md
whose frontmatter declares `type: folder` (i.e. the README is folder-meta,
not subject content like an advisor profile). Subject folders with a README
that declares `type: advisor`, `type: team-member`, or similar are skipped —
their README *is* the content.

Usage:
    scripts/rebuild-indexes.py                # regenerate all folder INDEXes
    scripts/rebuild-indexes.py sources/       # regenerate only sources/
    scripts/rebuild-indexes.py --check        # exit 1 if any INDEX is stale
    scripts/rebuild-indexes.py --check sources/

INDEX.md format (auto-generated, do not hand-edit):
    <!-- Generated by scripts/rebuild-indexes.py — do not edit by hand -->
    # <folder>/ — contents

    ## Files
    - [name.md](name.md) — description

    ## Subfolders
    - [sub/](sub/) — description

Sort order: files by filename desc (so date-prefixed files land newest-first),
then alpha; subfolders alpha.
"""

import argparse
import re
import sys
from fnmatch import fnmatch
from pathlib import Path

try:
    import yaml
except ImportError:
    print("rebuild-indexes: PyYAML missing. Install: pip install pyyaml", file=sys.stderr)
    sys.exit(2)

REPO_ROOT = Path(__file__).resolve().parent.parent
SCHEMA_PATH = REPO_ROOT / "schema" / "kb-schema.yaml"
GENERATED_HEADER = "<!-- Generated by scripts/rebuild-indexes.py — do not edit by hand -->"


def _load_exempt_patterns():
    """Read lint_exempt_patterns from schema so generator and lint stay in sync."""
    try:
        with open(SCHEMA_PATH) as f:
            schema = yaml.safe_load(f)
        return schema.get("lint_exempt_patterns", []) or []
    except (OSError, yaml.YAMLError):
        return []


EXEMPT_PATTERNS = _load_exempt_patterns()


def is_exempt(path: Path) -> bool:
    """True if path matches a lint_exempt_pattern — generator also skips it."""
    try:
        rel = str(path.relative_to(REPO_ROOT))
    except ValueError:
        return False
    for pat in EXEMPT_PATTERNS:
        if fnmatch(rel, pat):
            return True
    return False


def parse_frontmatter(text):
    """Return frontmatter dict or None if absent / invalid."""
    if not text.startswith("---\n") and not text.startswith("---\r\n"):
        return None
    lines = text.splitlines(keepends=True)
    end_idx = None
    for i in range(1, len(lines)):
        if lines[i].startswith("---"):
            end_idx = i
            break
    if end_idx is None:
        return None
    fm_text = "".join(lines[1:end_idx])
    try:
        fm = yaml.safe_load(fm_text)
    except yaml.YAMLError:
        return None
    return fm if isinstance(fm, dict) else None


def read_frontmatter(path: Path):
    try:
        text = path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return None
    return parse_frontmatter(text)


def folder_description(folder: Path):
    """Return (type, description) from folder's README.md, or (None, None)."""
    readme = folder / "README.md"
    if not readme.exists():
        return None, None
    fm = read_frontmatter(readme)
    if not fm:
        return None, None
    return fm.get("type"), fm.get("description")


def file_description(path: Path):
    """Return description from a content file's frontmatter, or None."""
    fm = read_frontmatter(path)
    if not fm:
        return None
    return fm.get("description")


def is_folder_meta(folder: Path) -> bool:
    """True if folder has a README.md declaring type: folder."""
    t, _ = folder_description(folder)
    return t == "folder"


def list_children(folder: Path):
    """Return (content_files, subfolders) for the folder.

    content_files: *.md in this folder (direct, not recursive), excluding
    README.md, INDEX.md, and anything matching schema lint_exempt_patterns
    (navigational docs, schema/, scripts/, etc. — not content).
    subfolders: immediate subdirectories, skipping dotfiles + exempt dirs.
    """
    content_files = []
    subfolders = []
    for entry in sorted(folder.iterdir()):
        if entry.name.startswith("."):
            continue
        if is_exempt(entry):
            continue
        if entry.is_file() and entry.suffix == ".md":
            if entry.name in ("README.md", "INDEX.md"):
                continue
            content_files.append(entry)
        elif entry.is_dir():
            subfolders.append(entry)
    # Sort files: by name desc so YYYY-MM-DD prefixes land newest-first.
    content_files.sort(key=lambda p: p.name, reverse=True)
    # Sort subfolders: alpha asc.
    subfolders.sort(key=lambda p: p.name)
    return content_files, subfolders


def render_index(folder: Path) -> str:
    """Build the INDEX.md content for this folder."""
    rel = folder.relative_to(REPO_ROOT) if folder != REPO_ROOT else Path(".")
    header_title = "root/" if folder == REPO_ROOT else f"{rel}/"

    content_files, subfolders = list_children(folder)

    lines = [
        GENERATED_HEADER,
        "",
        f"# {header_title} — contents",
        "",
    ]

    if content_files:
        lines.append("## Files")
        lines.append("")
        for f in content_files:
            desc = file_description(f)
            if desc:
                lines.append(f"- [{f.name}]({f.name}) — {desc}")
            else:
                lines.append(f"- [{f.name}]({f.name}) — _(no description)_")
        lines.append("")

    # Filter subfolders: only include those that have a README.md (of any type),
    # OR any content. Skip archive/, runs/, .git-like dirs at root level.
    displayable_subs = []
    for sub in subfolders:
        sub_type, sub_desc = folder_description(sub)
        has_content = any(
            p.suffix == ".md" and p.name not in ("INDEX.md",)
            for p in sub.iterdir() if p.is_file()
        )
        if sub_type is not None or has_content:
            displayable_subs.append((sub, sub_type, sub_desc))

    if displayable_subs:
        lines.append("## Subfolders")
        lines.append("")
        for sub, sub_type, sub_desc in displayable_subs:
            if sub_desc:
                lines.append(f"- [{sub.name}/]({sub.name}/) — {sub_desc}")
            else:
                lines.append(f"- [{sub.name}/]({sub.name}/) — _(no description)_")
        lines.append("")

    if not content_files and not displayable_subs:
        lines.append("_(empty)_")
        lines.append("")

    return "\n".join(lines)


def find_folder_metas(root: Path, scope: Path = None):
    """Yield folders (under scope) whose README.md has type: folder.

    If scope is None, walk from REPO_ROOT. scope may be a single folder,
    in which case we only check that folder (not its descendants).
    """
    if scope is not None:
        if is_folder_meta(scope):
            yield scope
        return
    for path in root.rglob("README.md"):
        # Skip .git, node_modules, etc.
        if any(part.startswith(".") for part in path.relative_to(root).parts):
            continue
        folder = path.parent
        if is_folder_meta(folder):
            yield folder


def process_folder(folder: Path, check_only: bool) -> bool:
    """Write INDEX.md for folder (or verify in --check mode).

    Returns True if file is up-to-date (or was written). False if --check
    found a diff.
    """
    new_content = render_index(folder)
    index_path = folder / "INDEX.md"
    existing = None
    if index_path.exists():
        try:
            existing = index_path.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            existing = None

    if existing is not None and existing.rstrip() == new_content.rstrip():
        return True  # no change needed

    if check_only:
        rel = index_path.relative_to(REPO_ROOT)
        print(f"rebuild-indexes --check: stale: {rel}", file=sys.stderr)
        return False

    # ensure trailing newline
    if not new_content.endswith("\n"):
        new_content += "\n"
    index_path.write_text(new_content, encoding="utf-8")
    rel = index_path.relative_to(REPO_ROOT)
    print(f"rebuild-indexes: wrote {rel}")
    return True


def main(argv):
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[1])
    parser.add_argument(
        "targets", nargs="*",
        help="Folder(s) to regenerate; default: all folders with type:folder README",
    )
    parser.add_argument(
        "--check", action="store_true",
        help="Verify on-disk INDEX.md files are up-to-date; exit 1 if stale",
    )
    args = parser.parse_args(argv)

    folders = []
    if args.targets:
        for t in args.targets:
            p = Path(t)
            if not p.is_absolute():
                p = (Path.cwd() / p).resolve()
            if not p.exists() or not p.is_dir():
                print(f"rebuild-indexes: {t}: not a directory", file=sys.stderr)
                return 2
            for f in find_folder_metas(REPO_ROOT, scope=p):
                folders.append(f)
    else:
        folders = list(find_folder_metas(REPO_ROOT))

    if not folders:
        if args.targets:
            print(f"rebuild-indexes: no folder-meta README in target(s); nothing to do")
        else:
            print(f"rebuild-indexes: no folder-meta READMEs found in repo; nothing to do")
        return 0

    all_ok = True
    for folder in folders:
        ok = process_folder(folder, check_only=args.check)
        if not ok:
            all_ok = False

    if args.check and not all_ok:
        print(
            "rebuild-indexes --check: at least one INDEX.md is stale. "
            "Run `python3 scripts/rebuild-indexes.py` and re-stage.",
            file=sys.stderr,
        )
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
